### ISSUE TITLE
Create a Video About Using the Screen Toolkit with Goose 🦢

### ISSUE THREAD

**Issue by blackgirlbytes** [block-open-source/goose-plugins#25]
# Create a Video About Using the Screen Toolkit with Goose 🦢
[Goose](https://github.com/block/goose) is your on-machine developer agent, automating engineering tasks seamlessly within your IDE or terminal. Guided by you, it can intelligently assess your project's needs, generate code modifications, and implement changes on its own.
Learn more about Goose in our [documentation](https://block.github.io/goose/).

Once your content is merged, it will be featured on our [Community Content site](https://block-open-source.github.io/goose-plugins/)!

## Example videos
https://github.com/user-attachments/assets/0217fc29-3b0b-4ab5-8a60-2dc53eb2b293

https://github.com/user-attachments/assets/5497112f-7ebb-4e73-9611-191be6d1934f

## 🚀 Goal
Create a comprehensive horizontal video tutorial (standard YouTube format, 16:9 aspect ratio) showing how to use the Screen Toolkit in Goose. Help others understand how this toolkit can be used for debugging, design work, and other creative applications by giving Goose the ability to see and analyze your screen.

## 🤝 How You Can Contribute
Create video content about:
- Setting up the Screen Toolkit
- Using screenshots for debugging
- Design assistance workflows
- UI/UX improvements with Goose
- Creative applications you've discovered
- Tips and best practices
- Integration with other toolkits

## 🔑 Tasks and Acceptance Criteria
- [ ] Create a video about using the Screen Toolkit
- [ ] Host your video on YouTube
- [ ] Add your content to the `content/content.json` file
- [ ] Create a pull request with your changes

Your contribution in content.json must include:
```
{
    "type": "video",
    "thumbnail": "./img/your-thumbnail.png",
    "title": "Your Video Title",
    "link": "https://youtube.com/your-video",
    "contributor": "Your Name"
}
```

## 🌟 Resources
- [Goose Documentation](https://block.github.io/goose/)
- [Goose repo](https://github.com/block/goose)
- [Screen Toolkit Documentation](https://block.github.io/goose/plugins/available-toolkits.html#5-screen-toolkit)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch
3. Create your video
4. Submit a PR with your content.json addition
5. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue!
Happy filming! 🦢

Would you like me to provide any of the other versions (blog, short, social) separately?

**Comment by aazam-gh** [comment]
.take

**Comment by blackgirlbytes** [comment]
Kind reminder that Loose Goose November ends November 20 at 11:59 pm ET, so if you wanted to be eligible for prizes, you only have a few hours left, but if you just want to work on this for fun after the deadline then let me know!
