### ISSUE TITLE
Create a Short (YouTube, IG Reel, or TikTok) About Using .goosehints Files with Goose 🦢

### ISSUE THREAD

**Issue by blackgirlbytes** [block-open-source/goose-plugins#30]
# Create a Short Video About Using .goosehints Files with Goose 🦢
[Goose](https://github.com/block/goose) is your on-machine developer agent, automating engineering tasks seamlessly within your IDE or terminal. Guided by you, it can intelligently assess your project's needs, generate code modifications, and implement changes on its own.
Learn more about Goose in our [documentation](https://block.github.io/goose/).

Once your content is merged, it will be featured on our [Community Content site](https://block-open-source.github.io/goose-plugins/)!

## Example clips
https://github.com/user-attachments/assets/0217fc29-3b0b-4ab5-8a60-2dc53eb2b293 

https://github.com/user-attachments/assets/5497112f-7ebb-4e73-9611-191be6d1934f

## 🚀 Goal
Create a vertical short-form video (YouTube Shorts, TikTok, Instagram Reel) demonstrating a quick tip or feature of .goosehints files with Goose. These should be under 60 seconds and in vertical format (9:16 aspect ratio).

## 🤝 How You Can Contribute
Create a quick demo showing:
- Quick setup of .goosehints
- A useful templating tip
- Real project example
- Cool use cases
- Quick tips and tricks
- Time-saving hints setup

## 🔑 Tasks and Acceptance Criteria
- [ ] Create a short video about using .goosehints files
- [ ] Host your content on your preferred platform
- [ ] Add your content to the `content/content.json` file
- [ ] Create a pull request with your changes

Your contribution in content.json must include:
```
{
    "type": "short",
    "thumbnail": "./img/your-thumbnail.png",
    "title": "Your Short Title",
    "link": "https://platform.com/your-short",
    "contributor": "Your Name"
}
```

## 🌟 Resources
- [Goose Documentation](https://block.github.io/goose/)
- [Goose repo](https://github.com/block/goose)
- [.goosehints Documentation](https://block.github.io/goose/guidance/getting-started.html#goosehints)
- [How to use toolkits](https://dev.to/blackgirlbytes/how-my-ai-dev-agent-turns-screenshots-into-ui-updates-189p)
- [How to create toolkits](https://dev.to/blackgirlbytes/how-to-extend-your-ai-agent-for-custom-developer-workflows-4fld)

## Full episodes on Goose to understand more

[![How to Build an AI-Powered GitHub Action](https://img.youtube.com/vi/lppDgrHY88Y/0.jpg)](https://www.youtube.com/watch?v=lppDgrHY88Y)

[![Upgrade U: Supercharging IntelliJ with an Open Source AI Agent](https://img.youtube.com/vi/Z4jF4SrbY2c/0.jpg)](https://www.youtube.com/watch?v=Z4jF4SrbY2c)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch
3. Create your short
4. Submit a PR with your content.json addition
5. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue!
Happy creating! 🦢

**Comment by Lymah123** [comment]
.take
