### ISSUE TITLE
Write a Blog Post: Creating Custom Plans with plan.md in Goose 🦢

### ISSUE THREAD

**Issue by blackgirlbytes** [block-open-source/goose-plugins#31]
# Write a Blog Post: Creating Custom Plans with plan.md in Goose 🦢
[Goose](https://github.com/block/goose) is your on-machine developer agent, automating engineering tasks seamlessly within your IDE or terminal. Guided by you, it can intelligently assess your project's needs, generate code modifications, and implement changes on its own.
Learn more about Goose in our [documentation](https://block.github.io/goose/).

Once your content is merged, it will be featured on our [Community Content site](https://block-open-source.github.io/goose-plugins/)!

## Example clips
https://github.com/user-attachments/assets/0217fc29-3b0b-4ab5-8a60-2dc53eb2b293 

https://github.com/user-attachments/assets/5497112f-7ebb-4e73-9611-191be6d1934f

## 🚀 Goal
Write a blog post explaining how to effectively use plan.md files with Goose. Help others understand how these files can define execution plans and improve Goose's task management.

## 🤝 How You Can Contribute
Write about things like:
- What are plan.md files and why use them
- Creating your first plan.md file
- Using Jinja templating in plans
- Passing arguments to plans
- Best practices and tips
- Real-world examples
- Creative ways to structure plans

## 🔑 Tasks and Acceptance Criteria
- [ ] Write a blog post about using plan.md files
- [ ] Host your blog post on your preferred platform (dev.to, Medium, personal blog, etc.)
- [ ] Add your content to the `content/content.json` file
- [ ] Create a pull request with your changes

Your contribution in content.json must include:
```
{
    "type": "blog",
    "thumbnail": "./img/your-thumbnail.png",
    "title": "Your Blog Post Title",
    "link": "https://linktoyourblog.com",
    "contributor": "Your Name"
}
```

## 🌟 Resources
- [Goose Documentation](https://block.github.io/goose/)
- [Goose repo](https://github.com/block/goose)
- [plan.md Documentation](https://block.github.io/goose/guidance/getting-started.html#plans)
- [How to use toolkits](https://dev.to/blackgirlbytes/how-my-ai-dev-agent-turns-screenshots-into-ui-updates-189p)
- [How to create toolkits](https://dev.to/blackgirlbytes/how-to-extend-your-ai-agent-for-custom-developer-workflows-4fld)

## Full episodes on Goose to understand more

[![How to Build an AI-Powered GitHub Action](https://img.youtube.com/vi/lppDgrHY88Y/0.jpg)](https://www.youtube.com/watch?v=lppDgrHY88Y)

[![Upgrade U: Supercharging IntelliJ with an Open Source AI Agent](https://img.youtube.com/vi/Z4jF4SrbY2c/0.jpg)](https://www.youtube.com/watch?v=Z4jF4SrbY2c)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch
3. Write your blog post
4. Submit a PR with your content.json addition
5. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue!
Happy writing! 🦢

Would you like me to create the video, short, and social versions too?

**Comment by Nabhel** [comment]
.take

**Comment by blackgirlbytes** [comment]
@Nabhel thanks for picking up this issue. I have a video here that might help you understand custom plans a bit more and Goose a bit more. i would start it at 5:03 minutes to skip the rest of the stuff that I talk about https://www.canva.com/design/DAGWg-PfVmM/xoNC2AeMqsrsIpCfifw6xA/watch

**Comment by blackgirlbytes** [comment]
Kind reminder that Loose Goose November ends November 20 at 11:59 pm ET, so if you wanted to be eligible for prizes, you only have a few hours left, but if you just want to work on this for fun after the deadline then let me know!

**Comment by Nabhel** [comment]
@blackgirlbytes Thank you for the video tutorial you shared, it really helped me watched it over and over to understand how to run goose. Although I'm not sure I can make it for any prizes, I want to keep working on some of the open issue to learn and get better at contributing. Thank you.

**Comment by KiranBaliga** [comment]
@Nabhel As a fellow contributor, I appreciate your efforts for creating a nice blog post! Also, congratulations in winning the dev.to writing challenge for your post : "My hactoberfest experience with TBD". ✨💫🧨

**Comment by Nabhel** [comment]
@KiranBaliga Thanks so much. 🙏
