### ISSUE TITLE
Create a Video About Creating Custom Plans with plan.md in Goose 🦢

### ISSUE THREAD

**Issue by blackgirlbytes** [block-open-source/goose-plugins#34]
# Create a Video About Creating Custom Plans with plan.md in Goose 🦢
[Goose](https://github.com/block/goose) is your on-machine developer agent, automating engineering tasks seamlessly within your IDE or terminal. Guided by you, it can intelligently assess your project's needs, generate code modifications, and implement changes on its own.
Learn more about Goose in our [documentation](https://block.github.io/goose/).

Once your content is merged, it will be featured on our [Community Content site](https://block-open-source.github.io/goose-plugins/)!

## Example videos
https://github.com/user-attachments/assets/0217fc29-3b0b-4ab5-8a60-2dc53eb2b293 

https://github.com/user-attachments/assets/5497112f-7ebb-4e73-9611-191be6d1934f

## 🚀 Goal
Create a comprehensive horizontal video tutorial (standard YouTube format, 16:9 aspect ratio) showing how to effectively use plan.md files with Goose. Help others understand how these files can define execution plans and improve Goose's task management.

## 🤝 How You Can Contribute
Create video content about:
- What are plan.md files and why use them
- Creating your first plan.md file
- Using Jinja templating in plans
- Passing arguments to plans
- Best practices and tips
- Real-world examples
- Creative ways to structure plans

## 🔑 Tasks and Acceptance Criteria
- [ ] Create a video about using plan.md files
- [ ] Host your video on YouTube
- [ ] Add your content to the `content/content.json` file
- [ ] Create a pull request with your changes

Your contribution in content.json must include:
```
{
    "type": "video",
    "thumbnail": "./img/your-thumbnail.png",
    "title": "Your Video Title",
    "link": "https://youtube.com/your-video",
    "contributor": "Your Name"
}
```

## 🌟 Resources
- [Goose Documentation](https://block.github.io/goose/)
- [Goose repo](https://github.com/block/goose)
- [plan.md Documentation](https://block.github.io/goose/guidance/getting-started.html#plans)

## Full episodes on Goose to understand more
[![How to Build an AI-Powered GitHub Action](https://img.youtube.com/vi/lppDgrHY88Y/0.jpg)](https://www.youtube.com/watch?v=lppDgrHY88Y)

[![Upgrade U: Supercharging IntelliJ with an Open Source AI Agent](https://img.youtube.com/vi/Z4jF4SrbY2c/0.jpg)](https://www.youtube.com/watch?v=Z4jF4SrbY2c)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch
3. Create your video
4. Submit a PR with your content.json addition
5. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue!
Happy filming! 🦢
