### ISSUE TITLE
Create Your Own Toolkit for Goose! 🛠️

### ISSUE THREAD

**Issue by blackgirlbytes** [block-open-source/goose-plugins#61]
Here's the revised issue template for creating toolkits:

# Create Your Own Toolkit for Goose! 🛠️

[Goose](https://github.com/block/goose) extends its capabilities through toolkits. Share your custom toolkit to help other developers automate their workflows!

## 🎯 Goal
Create a custom toolkit for Goose and contribute it to our [community plugins](https://github.com/block-open-source/goose-plugins/tree/main/src/goose_plugins/toolkits).

## 🔑 Tasks and Acceptance Criteria
- [ ] Design and implement your toolkit
- [ ] Test your toolkit locally
- [ ] Write tests for your toolkit -- see here for an [example](https://github.com/block-open-source/goose-plugins/blob/main/tests/toolkits/test_todo.py)
- [ ] Add your toolkit to the goose-plugins repository
- [ ] Create a pull request with your changes

Your toolkit should:
- Solve a specific development workflow challenge
- Include clear documentation
- Follow Goose's toolkit structure
- Include tests where appropriate

## 🎓 Resources
- [Goose Documentation](https://block.github.io/goose/)
- [Goose repo](https://github.com/block/goose)
- [How to use toolkits](https://dev.to/blackgirlbytes/how-my-ai-dev-agent-turns-screenshots-into-ui-updates-189p)
- [How to create toolkits](https://dev.to/blackgirlbytes/how-to-extend-your-ai-agent-for-custom-developer-workflows-4fld)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch
3. Develop your toolkit
4. Submit a PR adding your toolkit to the `/src/goose_plugins/toolkits` directory
5. Wait for review and address any feedback

## Questions?
Need help or clarification? Comment on this issue!

Happy coding! 🦢

**Comment by adalundhe** [comment]
I heard y’all need some Python toolkits! On it’

**Comment by adalundhe** [comment]
.take

**Comment by blackgirlbytes** [comment]
YAY let me know if you need help. It took me awhile to figure out. Here's the toolkit I made: https://dev.to/blackgirlbytes/how-to-extend-your-ai-agent-for-custom-developer-workflows-4fld

Here's other toolkits made by people in our company: https://github.com/block/goose/tree/main/src/goose/toolkit
Here's what each of them do: https://block.github.io/goose/plugins/available-toolkits.html
Here's some documentation on creating toolkits: https://block.github.io/goose/plugins/creating-a-new-toolkit.html

You are the best @adalundhe 

Also if you see me create duplicate issues of this..it's just to see if other people want to create toolkits as well

**Comment by Talesconnect** [comment]
.take

**Comment by blackgirlbytes** [comment]
Kind reminder that Loose Goose November ends November 20 at 11:59 pm ET, so if you wanted to be eligible for prizes, you only have a few hours left, but if you just want to work on this for fun after the deadline then let me know!
