### ISSUE TITLE
Create Your Own Toolkit for Goose! 🛠️

### ISSUE THREAD

**Issue by blackgirlbytes** [block-open-source/goose-plugins#62]
# Create Your Own Toolkit for Goose! 🛠️

[Goose](https://github.com/block/goose) extends its capabilities through toolkits. Share your custom toolkit to help other developers automate their workflows!

## 🎯 Goal
Create a custom toolkit for Goose and contribute it to our [community plugins](https://github.com/block-open-source/goose-plugins/tree/main/src/goose_plugins/toolkits).

## 🔑 Tasks and Acceptance Criteria
- [ ] Design and implement your toolkit
- [ ] Test your toolkit locally
- [ ] Write tests for your toolkit -- see here for an [example](https://github.com/block-open-source/goose-plugins/blob/main/tests/toolkits/test_todo.py)
- [ ] Add your toolkit to the goose-plugins repository
- [ ] Create a pull request with your changes

Your toolkit should:
- Solve a specific development workflow challenge
- Include clear documentation
- Follow Goose's toolkit structure
- Include tests where appropriate

## 🎓 Resources
- [Goose Documentation](https://block.github.io/goose/)
- [Goose repo](https://github.com/block/goose)
- [How to use toolkits](https://dev.to/blackgirlbytes/how-my-ai-dev-agent-turns-screenshots-into-ui-updates-189p)
- [How to create toolkits](https://dev.to/blackgirlbytes/how-to-extend-your-ai-agent-for-custom-developer-workflows-4fld)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch
3. Develop your toolkit
4. Submit a PR adding your toolkit to the `/src/goose_plugins/toolkits` directory
5. Wait for review and address any feedback

## Questions?
Need help or clarification? Comment on this issue!

Happy coding! 🦢

**Comment by Johnnyevans32** [comment]
.take

**Comment by blackgirlbytes** [comment]
@Johnnyevans32 right now creating toolkits is not super documented..so definitely take a look at this https://dev.to/blackgirlbytes/how-to-extend-your-ai-agent-for-custom-developer-workflows-4fld and this for some additional guidance https://www.youtube.com/watch?v=tQtg7M5w_Ak

**Comment by Johnnyevans32** [comment]
i keep getting this error when tryna run my toolkit @blackgirlbytes 

```
(env) jevan@Evanss-MacBook-Air goose-one % goose session start --profile demo-docgen                                  
Unknown toolkit: docgen. Available toolkits: browser, developer, github, jira, reasoner, repo_context, screen, synopsis.
```

 I already added the tool kit to my pyproject.toml

```
[project.entry-points."goose.toolkit"]
developer = "goose.toolkit.developer:Developer"
github = "goose.toolkit.github:Github"
jira = "goose.toolkit.jira:Jira"
screen = "goose.toolkit.screen:Screen"
reasoner = "goose.toolkit.reasoner:Reasoner"
repo_context = "goose.toolkit.repo_context.repo_context:RepoContext"
synopsis = "goose.synopsis.toolkit:SynopsisDeveloper"
browser = "goose.toolkit.web_browser:BrowserToolkit"
memory = "goose.toolkit.memory:Memory"
google_workspace = "goose.toolkit.google_workspace:GoogleWorkspace"
todo = "goose_plugins.toolkits.todo:TodoToolkit"
docgen = "goose_plugins.toolkits.docgen:DocGen"
```

**Comment by blackgirlbytes** [comment]
hmmm try running this `uv run goose session start` in goose-plugins and let me know what happens! @Johnnyevans32

**Comment by Johnnyevans32** [comment]
thank you @blackgirlbytes , this is sorted now
